### ISSUE TITLE
Left-aligning insertion calls?

### ISSUE THREAD

**Issue by kautto** [lh3/minimap2#315] opened 2019-01-21 18:52 UTC
Hi @lh3, 

do you have any tips for trying to achieve something equivalent to "LeftAlignIndels" with minimap2? For example, with ONT data I'm seeing the called insertion position in a duplication jump around the whole duplication region. I don't know if the issue is inherent to the Nanopore error rate and profile, or if it's something that could be addressed with parameter tweaks. Can you think of any parameters I could change to try to cluster the insertion calls? (e.g. trying to get all the insertions to be called on the left in the image below, instead of across the region).

![annotation 2019-01-21 134630](https://user-images.githubusercontent.com/5281754/51493332-026b0480-1d83-11e9-8035-9109083c3973.jpg)

Thanks!

P.S. I did try the actual "LeftAlignIndels" tool and, not surprisingly, it doesn't really work too well with ONT data.

**Comment by lh3** [comment] 2019-01-21 19:02
Duplicate of #276.

Sequencing errors may shift the position of indels. There is little we can do without assembly or multi-sequence alignment.

**Closed** 2019-01-23 15:55 UTC
Labels: duplicate
