### ISSUE TITLE
Warning: no @SQ lines will be outputted

### ISSUE THREAD

**Issue by kanchanhole** [lh3/minimap2#58] opened 2017-11-13 19:02 UTC
I am working on Oxford nanopore reads(1D). I am using Minimap2 for aligning it to the human genome. I made an index file for the human genome to be used as a reference. when I started the alignment I got following warning.
"For a multi-part index, no @SQ lines will be outputted"
The alignment is finished. The .sam file does not contain any @SQ headers, as a result, I could not get any mapping statistics using samtools flagstat. 
The command I used for building index:

minimap2 -d ref.mmi ref.fa

The command I used for alignment:

minimap2 -ax map-ont ref.fa ont-reads.fa > aln.sam
I am not sure why I am getting this warning.

**Comment by lh3** [comment] 2017-11-13 19:03
What reference genome are you using? What is the total length of all sequences in `ref.fa`? Thanks.

**Comment by kanchanhole** [comment] 2017-11-13 19:05
Homo_sapiens.GRCh38.fa

Human genome built 38

**Comment by lh3** [comment] 2017-11-13 19:12
Is this "toplevel" file from Ensembl? If yes, you should use [this file][1] (click to download). The full URL is (very long):
```
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
```

[1]: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

**Comment by kanchanhole** [comment] 2017-11-13 19:13
Is this human genome?

**Comment by lh3** [comment] 2017-11-13 19:14
Ensembl's "toplevel" fasta is very confusing and should be avoided in general. See this discussion [here](https://github.com/lh3/minimap2/issues/37#issuecomment-336998722).

**Comment by lh3** [comment] 2017-11-13 19:15
The FTP link above is the official version from GRC.

**Comment by kanchanhole** [comment] 2017-11-13 19:16
Thank you very much. If I download the "Reference Genome Sequence" from:[https://www.ncbi.nlm.nih.gov/projects/genome/guide/human/](URL)

will it work fine?

**Comment by kanchanhole** [comment] 2017-11-13 19:21
Thank you very much. I have started the index building again with the link you provided.

**Comment by lh3** [comment] 2017-11-13 19:23
Your new link doesn't give you chromosome sequences, apparently. Anyway, the right GRCh38 for most analyses is the FTP link above. It seems that I need to write a blog post to explain the differences between the different versions...

**Comment by lh3** [comment] 2017-11-13 19:24
I will keep this open until you confirm minimap2 works properly. Meanwhile, I will write a blog post to explain the different genome versions.

**Comment by kanchanhole** [comment] 2017-11-13 19:52
Hello, 
The alignment runs fine. Thank you very much.

However, how does minimap2 creates a stat file.
showing statistics like overall mapping? uniquely mapping?

**Comment by lh3** [comment] 2017-11-13 20:04
Unfortunately, minimap2 doesn't keep track of these information. You have to use 3rd-party tools like `samtools flagstat`, `samtools stats` or others to collect the info as a separate step.

**Comment by kanchanhole** [comment] 2017-11-13 20:05
Okay. Sure.

Thank you very much for the help. I really appreciate it.

**Comment by lh3** [comment] 2017-11-13 20:05
Welcome. I am closing the issue now. Thanks!

**Comment by kanchanhole** [comment] 2017-12-03 17:14
Hello, 

Is there any way I could download the official version of GRC for build 37? 
The link you suggested above gives for 38. 

I greatly appreciate your help. Thank you.

**Comment by attractivechaos** [comment] 2017-12-03 17:28
http://lh3.github.io/2017/11/13/which-human-reference-genome-to-use

**Comment by lh3** [comment] 2017-12-03 17:28
http://lh3.github.io/2017/11/13/which-human-reference-genome-to-use

**Comment by kanchanhole** [comment] 2017-12-03 17:30
Thank you very much. This is really helpful.

**Comment by kanchanhole** [comment] 2017-12-04 01:22
Hello, as per your blog I have used the reference GRCh 37 in my alignment. However, when I try to visualize the alignment in IGV (using the GRCh37/hg19 included in IGV) I could not see the specific gene I am interested in with the coordinates I have. (which I could see with GRCh38.)

Do I  need to download gene list for the reference you provided and load the genome on IGV?

**Comment by AnjuniPeiris** [comment] 2018-02-22 00:59
Hi, I'm running minimap2 on a reference genome for wheat stripe rust and having the same issue, and receive this error message:

[WARNING] For a multi-part index, no @SQ lines will be outputted.

Here's the reference genome: http://mbio.asm.org/content/9/1/e02275-17
It's a small genome but we are getting this error message even when mapping for just the primary genome assembly, without haplotypes. We are not getting the mapping statistics either. Any advice to solve this issue?
Thanks.

**Comment by lh3** [comment] 2018-02-22 01:37
Could you send me the exact reference fasta to me? Thanks.

**Comment by AnjuniPeiris** [comment] 2018-02-22 02:53
The reference fasta are available here:
https://github.com/BenjaminSchwessinger/Pst_104_E137_A-_genome/tree/master/Assembly

I used the 'Pst_104E_v13_p_ctg.fa' file and also combined it with the 'Pst_104E_v13_h_ctg.fa' to get the primary and haplotype assembly.

**Comment by lh3** [comment] 2018-02-22 02:57
Could you put the ***exact*** fasta you use somewhere? If this is a bug, it will only happen in extreme cases. Files created at my hand may not reproduce the issue. Thank you.

**Comment by lh3** [comment] 2018-02-22 03:03
Also, what is the command line and the version of minimap2 are you using? (BTW, I am unable to reproduce the issue on my machine)

**Comment by AnjuniPeiris** [comment] 2018-02-23 01:10
I'm using minimap2 version 2.8-r711.

Here is the link to the exact fasta files and also the fastq inputs I used for mapping:
https://anu365-my.sharepoint.com/personal/u5587237_anu_edu_au/_layouts/15/onedrive.aspx?slrid=ae254d9e-a034-5000-27e2-fb6b08e169ce&id=%2Fpersonal%2Fu5587237_anu_edu_au%2FDocuments%2Fminimap_inputs&FolderCTID=0x012000AB71B6903A88AA4C88946B5BD9284013

I tried mapping to the primary and haplotype (ph) reference genome, and then only the primary (p), but still get the same SQ error. Both the reference genomes are in the linked file.

Here is the command line:
~/myapps/minimap2/minimap2/minimap2 -ax map-ont ${PBS_JOBFS}/albacore_fastq/${name}_pass.fastq ${PBS_JOBFS}/GENOME/${genome_file} > ${name}_pass.minimap2.out.sam
~/myapps/minimap2/minimap2/minimap2 -ax map-ont ${PBS_JOBFS}/albacore_fastq/${name}_fail.fastq ${PBS_JOBFS}/GENOME/${genome_file} > ${name}_fail.minimap2.out.sam

**Comment by lh3** [comment] 2018-02-23 01:14
> ~/myapps/minimap2/minimap2/minimap2 -ax map-ont ${PBS_JOBFS}/albacore_fastq/${name}_pass.fastq ${PBS_JOBFS}/GENOME/${genome_file} > ${name}_pass.minimap2.out.sam

When you map to a reference genome, the reference fasta should be the first argument. You are putting the reference as the second argument.

**Comment by lh3** [comment] 2018-02-23 01:15
I mean: the command line should be:

> ~/myapps/minimap2/minimap2/minimap2 -ax map-ont ${PBS_JOBFS}/GENOME/${genome_file} ${PBS_JOBFS}/albacore_fastq/${name}_pass.fastq > ${name}_pass.minimap2.out.sam

Anyway, thanks for reporting!

**Closed** 2018-02-24 14:55 UTC
Labels: duplicate, question

**Comment by jtamames** [comment] 2021-01-07 15:31
Hello

Congrats for this excellent and useful software!
We are using minimap2 in our metagenomics pipeline [SqueezeMeta](https://github.com/jtamames/SqueezeMeta) to map metagenomic reads to assembled contigs. One of our users ran into a problem when mapping PacBio samples. Here you can see the command line:

> Mapping with Minimap2 (Li 2018, Bioinformatics 34(18), 3094-3100)
Working with sample 1: SampleI
Getting raw reads
Aligning to reference with minimap2-pb
...........
Version: 2.12-r827
CMD: /home/mphilipp/anaconda3/envs/SQM1.3/SqueezeMeta/bin/minimap2 -ax asm20 -t 70 /scratch/mphilipp/msm89/08_sqm/mg02_canu2_hifi2/results/01.mg02_canu2_hifi2.fasta /scratch/mphilipp/msm89/08_sqm/mg02_canu2_hifi2/temp/mg02_canu2_hifi2.SampleI.current_1
Real time: 1498.507 sec; CPU: 68155.684 sec

The problem is that no `@SQ` headers are present in the resulting SAM. I have seen that this was sometimes due to a incorrect command line where reads were specified bafore reference, but this is not our case. Could you hint us about the problem here?

Best,
Javier

**Comment by lh3** [comment] 2021-01-07 15:36
See README.
