### ISSUE TITLE
Seg fault in 100 bp reads

### ISSUE THREAD

**Issue by cnk113** [lh3/minimap2#362] opened 2019-03-11 20:25 UTC
So I'm running some data from the 1000 Genomes project which had 100 bp reads.
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/1000genomes.sequence.index
search for ERR240726_1.fastq.gz
I preindexed hg19 using -x sr parameters.

minimap2 -t 8 -a hg19.mmi ERR240726_1.fastq.gz > test
[M::main::10.945*1.00] loaded/built the index for 24 target sequence(s)
[M::mm_mapopt_update::14.531*1.00] mid_occ = 105
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 24
[M::mm_idx_stat::16.996*1.00] distinct minimizers: 379832425 (95.56% are singletons); average occurrences: 1.259; average spacing: 6.472
minimap2-2.15_x64-linux/minimap2: Segmentation fault

I'm running it with 64 GB of memory.

**Comment by cnk113** [comment] 2019-03-11 20:37
Also this command works if I hash the reference and mapping.

minimap2 -t 8 -ax sr ucsc.hg19.fasta ERR240726_1.fastq.gz > test
[M::mm_idx_gen::43.445*1.47] collected minimizers
[M::mm_idx_gen::47.010*1.95] sorted minimizers
[M::main::47.010*1.95] loaded/built the index for 24 target sequence(s)
[M::mm_mapopt_update::47.010*1.95] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 24
[M::mm_idx_stat::49.452*1.90] distinct minimizers: 379832425 (95.56% are singletons); average occurrences: 1.259; average spacing: 6.472
[M::worker_pipeline::54.336*2.40] mapped 500000 sequences
[M::worker_pipeline::58.238*2.80] mapped 500000 sequences
[M::worker_pipeline::61.776*3.13] mapped 500000 sequences
[M::worker_pipeline::65.708*3.44] mapped 500000 sequences
[M::worker_pipeline::69.079*3.69] mapped 500000 sequences
[M::worker_pipeline::72.750*3.93] mapped 500000 sequences
[M::worker_pipeline::76.350*4.13] mapped 500000 sequences
[M::worker_pipeline::79.912*4.27] mapped 500000 sequences
[M::worker_pipeline::79.992*4.27] mapped 43057 sequences
[M::main] Version: 2.15-r905
[M::main] CMD: minimap2-2.15_x64-linux/minimap2 -t 8 -ax sr ucsc.hg19.fasta ERR240726_1.fastq.gz
[M::main] Real time: 80.145 sec; CPU: 341.818 sec; Peak RSS: 13.322 GB

**Comment by lh3** [comment] 2019-03-11 20:50
You have to apply `-x sr` when mapping as well.

Nonetheless, this doesn't explain why minimap2 segfaults. Any segfaults are bad. I will have a look at some point.

**Comment by cnk113** [comment] 2019-03-11 21:07
That fixes the issue, thanks. Feel free to close this issue whenever.

**Comment by lh3** [comment] 2019-03-11 21:53
I will leave this open until I have time to investigate the segfault. Thanks for reporting.

**Comment by lh3** [comment] 2019-05-01 02:23
I could not reproduce the issue on my dataset. I will leave this open until someone reports similar issues.

**Comment by lh3** [comment] 2019-05-10 16:26
I will close this thread for now as I can't reproduce on my side. Others having a similar issue will probably create a new ticket.

**Closed by lh3** 2019-05-10 16:26 UTC
Labels: more info needed
