### ISSUE TITLE
--cs or -a option change alignment results

### ISSUE THREAD

**Issue by TristanLefebure** [lh3/minimap2#186] opened 2018-06-19 12:55 UTC
Dear Heng,

I am puzzled by how different can sometime be the output just by changing an output parameter. Here is an example with 2 reads to align on 1 contig (the goal is to perform fast assignation, i.e. find very similar sequences):

```bash
minimap2 -x sr COI_e.fasta Minima_bug.fasta

OTU_103 461     8       259     +       COI_e   639     206     457     42      251     12      tp:A:P  cm:i:2     s1:i:42 s2:i:0
OTU_29  461     21      436     +       COI_e   639     219     634     415     415     60      tp:A:P  cm:i:65    s1:i:415        s2:i:0
 ```

The read OTU_103 does not align well with an identity of 42/251, but then:

```bash
minimap2 -x sr COI_e.fasta Minima_bug.fasta --cs

OTU_103 461     0       260     +       COI_e   639     198     458     213     260     9       NM:i:47 ms:i:70    AS:i:58 nn:i:0  tp:A:P  cm:i:2  s1:i:42 s2:i:0  cs:Z::2*ca:2*ta:23*tc:15*ta:1*ga*tc:1*gt:5*tc:3*tc:1*at:2*ta*tc:1*at*tc:4*ga:2*gt:2*tc:2*ct*ta:4*ta:8*tg:5*ga:2*ta:8*ac:20*cg:2*at:5*ac:3*ga:1*ca:2*ag:2*tg:5*ta:2*tc*ac:1*at:11*ca:2*at:8*cg:2*ta*ga:1*ct:9*ct:4*ga:2*ta:2*ca:11*at:2*ta:23
OTU_29  461     0       441     +       COI_e   639     198     639     437     441     60      NM:i:4  ms:i:846   AS:i:846        nn:i:0  tp:A:P  cm:i:65 s1:i:415        s2:i:0  cs:Z::2*ct:8*ag:2*at:2*ct:423
```

Both alignments have changed, but the one for OTU_103 has dramatically changed (much shorter but with high ident = 213/260). Why would an output option impact the alignment?

Thanks for such a great software !
(done with version 2.10-r761)

Tristan

[COI_e.fasta.gz](https://github.com/lh3/minimap2/files/2115211/COI_e.fasta.gz)
[Minima_bug.fasta.gz](https://github.com/lh3/minimap2/files/2115212/Minima_bug.fasta.gz)

**Comment by lh3** [comment] 2018-06-19 13:51
Duplicate of #161 and #102. When --cs, -c or -a is used, minimap2 will do base-level alignment, which is much slower but gives you more accurate alignment most of time.

**Closed by lh3** 2018-06-19 13:51 UTC
Labels: duplicate, question
