### ISSUE TITLE
negative AS tag value when outputting SAM records

### ISSUE THREAD

**Issue by SHuang-Broad** [lh3/minimap2#192] opened 2018-06-25 22:12 UTC
Affected version:  latest release (2.11)

Command:

```bash
minimap2 -a -Q -t 4 -x asm5 \
  ~/Ref/Homo_sapiens_assembly38.fasta forMinimap2.fa | \
  samtools view -S -b | samtools sort -o forMinimap2.bam
```

The read sequence is generated from a local assembly looking for SV
```bash
$ cat forMinimap2.fa
@asm021835:tig00000
TCTGCTCCAATAATTCCACCCCTGACAATCTAGCTTTCATGAATAATTTTAAAAGTAGAAAAATTTGTGTAATAACATGTTATCAGAGTGTGGTTTAAATGAGCGAGCCATGGGCAGGCCACTCAAGTCCTGCAGCAGAAAGGAGATGGGGCAAATTCGGTTGCATCCAAGTGTCGGGTGTTAGTCACTAAAAACAGAACGTTTGATGGCCTGGAGATATGCTCGTGATTTGCAGCATGCTTTCAACGAGATGTTTTCCCTGTAAAAACAGCTTCATTGAGTTATAACTACATACAACAAACTAGGCATAATGAAACATGCACGACCCTAAGATTTTTATACTGGTGTACCGCGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACATAGGTGTACCCCGTGACCCAGCATCCAGGTGCGGGATGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCACACGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCATCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAATACAGGTGTACCCCGGGACCCAGCACCCACATGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGCACAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTG
```

```bash
$ samtools view forMinimap2.bam

asm021835:tig00000	0	chr13	113433899	60	428M1841S	*	0	0	TCTGCTCCAATAATTCCACCCCTGACAATCTAGCTTTCATGAATAATTTTAAAAGTAGAAAAATTTGTGTAATAACATGTTATCAGAGTGTGGTTTAAATGAGCGAGCCATGGGCAGGCCACTCAAGTCCTGCAGCAGAAAGGAGATGGGGCAAATTCGGTTGCATCCAAGTGTCGGGTGTTAGTCACTAAAAACAGAACGTTTGATGGCCTGGAGATATGCTCGTGATTTGCAGCATGCTTTCAACGAGATGTTTTCCCTGTAAAAACAGCTTCATTGAGTTATAACTACATACAACAAACTAGGCATAATGAAACATGCACGACCCTAAGATTTTTATACTGGTGTACCGCGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACATAGGTGTACCCCGTGACCCAGCATCCAGGTGCGGGATGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCACACGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCATCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAATACAGGTGTACCCCGGGACCCAGCACCCACATGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGCACAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTG	*	NM:i:0	ms:i:428	AS:i:428	nn:i:0	tp:A:P	cm:i:40	s1:i:406	s2:i:650	dv:f:0.0188	zd:i:1	SA:Z:chr13,113435729,+,1116S832M336D321S,60,368;chr13,113434276,+,377S265M126D1627S,60,127;
asm021835:tig00000	2048	chr13	113434276	60	377H240M126D25M1627H	*	0	0	TGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACATAGGTGTACCCCGTGACCCAGCATCCAGGTGCGGGATGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCACACGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCATCCACATGTAGAGTGAACACAGGTGT	*	NM:i:127	ms:i:220	AS:i:38	nn:i:0	tp:A:P	cm:i:18	s1:i:183	s2:i:650	dv:f:0.0188	zd:i:3	SA:Z:chr13,113433899,+,428M1841S,60,0;chr13,113435729,+,1116S832M336D321S,60,368;
asm021835:tig00000	2048	chr13	113435729	60	1116H24M42D336M294D472M321H	*	0	0	GGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAATACAGGTGTACCCCGGGACCCAGCACCCACATGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGCACAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCC*	NM:i:368	ms:i:241	AS:i:-306	nn:i:0	tp:A:P	cm:i:71	s1:i:720	s2:i:650	dv:f:0.0188	zd:i:3	SA:Z:chr13,113433899,+,428M1841S,60,0;chr13,113434276,+,377S265M126D1627S,60,127;
```
Running `bwa mem -x intractg ~/Ref/Homo_sapiens_assembly38.fasta forMinimap2.fa` returns

```
asm021835:tig00000	0	chr13	113433899	60	900M42D1090M279S	*	0	0	TCTGCTCCAATAATTCCACCCCTGACAATCTAGCTTTCATGAATAATTTTAAAAGTAGAAAAATTTGTGTAATAACATGTTATCAGAGTGTGGTTTAAATGAGCGAGCCATGGGCAGGCCACTCAAGTCCTGCAGCAGAAAGGAGATGGGGCAAATTCGGTTGCATCCAAGTGTCGGGTGTTAGTCACTAAAAACAGAACGTTTGATGGCCTGGAGATATGCTCGTGATTTGCAGCATGCTTTCAACGAGATGTTTTCCCTGTAAAAACAGCTTCATTGAGTTATAACTACATACAACAAACTAGGCATAATGAAACATGCACGACCCTAAGATTTTTATACTGGTGTACCGCGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACATAGGTGTACCCCGTGACCCAGCATCCAGGTGCGGGATGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCACACGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCATCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAATACAGGTGTACCCCGGGACCCAGCACCCACATGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGCACAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCAGCATCCACACGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGCGCAGGGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGCGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCACATGTAGAGTGAACACAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCATCCAGGCGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCCGGGACCCGGTACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCAGGTGTAGAGTGAACATAGGTGTACCCTGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCAGGACCCGGCACCCACGCATAGAGTGAACATAGGTGTACCCTGTGACCCAGCACCCAGGCGTAGAGTGAACATAGGTGTAGCCCGTGACCCAGCACCCAGTCGTAGAGTGAACATAGGTGTACCCCAGGACCTGGCACCCAGGTGTAGAGTGAACACAGGTGTACCCCGGGACCCAGCACCCAGGTGTAGAGTGAACATAGGTGTACCCCGGGACCCGGCACCCAGGTGTAGAGTG	*	NM:i:137	MD:Z:457A219C64C3C0A0T12C26G1T0G32C7C23T17C25^GGACCCGGCACCCATGCATAGAGTGAACATAGGTGTACCCCG40C42G14G1T0G11C10C1G5G9T20C4G5G8G0T30C23T10T42A14C1C0A11T10T1T11G3C4A26A11T2A5C20G8G0C0A22T1T16G0T8T9G2C1T17T2A19A5T0G3C3G0G0T31A11T2A68A9T1T29A9T12C10C15G0G55C41C10C7G3C5T39G1T0G11C20C39G22C11G6A14G18	AS:i:982	XS:i:541
```
-------

What's not expected:
The third SAM record has alignment score of negative value (AS:i:-306).
I'm not sure if this is related to the following comment from README:

> Minimap2 may produce suboptimal alignments through long low-complexity regions where seed positions may be suboptimal. This should not be a big concern because even the optimal alignment may be wrong in such regions.

considering [this region](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr13%3A113434039-113436539&hgsid=678380773_UwUAfoDHdf3MiZ85YehsxaZLvvRR) is not particularly easy on mappers.

Though in theory a negative AS possible, in practice it might be startling to users, as I've yet to see a negative AS from bwa mem.
And I'm wondering if filtering out alignments with negative AS values is a good practice.

Could you comment please?
Thanks!

**Comment by SHuang-Broad** [comment] 2018-06-26 00:05
In addition, there's a strange behavior regarding the first two alignments output by minimap2:

The first two alignments should be merged into a single one.

Alignment one has reference span 113433899-11343326, and read span 1-428.
Alignment two has reference span 113434276-11344666, and read span 378-642.

Notice the two alignments have overlap of 51bp on both the reference and read.

The combined alignment could have a start position of 113433899 and CIGAR 617M126D25M1627H

**Comment by lh3** [comment] 2018-06-26 01:33
A quick comment: `asm5` is used for sequences around 0.1% divergence. The divergence of your sequence is far above that. Probably the query is a distant paralog that doesn't belong to GRCh38. If you use a preset `asm20`, you will see one alignment.

> Notice the two alignments have overlap of 51bp on both the reference and read.

Probably that's because there are too many mismatches in this 51bp. Once you join the alignment, the alignment score drops too fast. Again, the root cause is that the sequence should not be mapped to GRCh38.

**Comment by SHuang-Broad** [comment] 2018-06-26 16:21
I see. I'll experiment with different parameters and see if that fits better to my problem.
Thanks!

**Comment by lh3** [comment] 2018-08-06 14:53
I am closing this. If you still see further issues, you may reopen the issue or add another comment. I will be notified by email. Thank you.

**Closed by lh3** 2018-08-06 14:53 UTC
Labels: question
