### ISSUE TITLE
Mapping Short reads on PacBio

### ISSUE THREAD

**Issue by francicco** [lh3/minimap2#419] opened 2019-06-06 09:47 UTC
Hi, 

Mine is a general question. Is it possible and reliable to map short illumina reads on onto long reads (PacBio/Nanopore)? What the best command line would be?

Thanks
Francesco

**Comment by lh3** [comment] 2019-06-06 13:45
Duplicate of #90, #214 and #407. Short answer: no good solutions.

**Closed by lh3** 2019-06-06 13:45 UTC
Labels: duplicate
