### ISSUE TITLE
want to get some advance about short RNA-seq data alignment and the output Sam file format from minimap2

### ISSUE THREAD

**Issue by 909089617xx** [lh3/minimap2#359] opened 2019-03-10 12:17 UTC
Hi heng,
I have been using STAR to deal with RNA-seq data(150bp pair-end) before, but due to the large genome size of wheat, the STAR  has some limitations, such as high memory and the chromosomes need to be truncated  . so I use minimap2 to map the RNA-seq data in order to find the difference between them.If minimap2 has the similar result and more faster . I will choose minimap2.
1.Here is my code(i want to get some advance about the parameters which can more suitable for short but accurate RNA-seq data):
$minimap2 -I 15g -t 15 --sr -ax splice -uf -C5 /data1/home/161010_Chinese_Spring_v1.0_pseudomolecules.fasta /data1/home/analysis0215/test-result/test-withoutERCC/subFastqs/3000000test-A01.fq > /data1/home/analysis0215/test-result/test-withoutERCC/3000000test-A01.sam
2.After getting the SAM file, I usually count using HTSeq, but there are some format issues when using the minimap2 SAM file.
In addition to some detailed information added in the header and footer, the following situation will happen-Some information is missing
![image](https://user-images.githubusercontent.com/33317454/54084857-2ef9d080-4371-11e9-9384-6a83c9453d1a.png)
best wishes!

**Comment by lh3** [comment] 2019-03-10 19:25
Minimap2 doesn't work well with short RNA-seq reads. If star is using too much memory, you should use hisat/hisat2 instead.

Nonetheless, malformatting should not be happening anyway. Could you upload that few lines? The screenshot is not that clear to me. Thanks.

**Comment by LipengKang** [comment] 2019-03-11 07:36
Hi, heng! 
malformatting? I use samtools to convert PacBio.minimap2.sam to bam. Following error appeared!
**[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 169557
[main_samview] truncated file.**

I cut line 169557-169558. It seems that String "[M::worker_pipeline::4302.783*13.85] mapped 38927 sequences" was added in QUAL and then newline.
```
m54267_181003_033514/9372084/35772_54170	2064	chr4A	158615966	60	16024H14M1D6M1D36M1I4M1D11M2D5M2D20M1D6M1D16M1I2M1I18M1D19M1D9M2D4M1D2M2D32M1I7M1D27M1D8M1D3M1D9M1D12M1D20M1I5M3D32M1D69M1D7M1D3M2I5M1I7M1D8M1I21M2I6M2D5M1D12M1I19M1D15M1D26M1D29M3I4D17M1D15M1D14M1I16M1D19M4I4M1I22M1D2M1D2M1D9M1D4M3I11M1D35M2I16M1D16M1D57M1D6M1D7M1I19M1I20M7I30M1D14M2I3M1D73M1D24M1I9M1I15M1D28M2D2M1D5M1D19M1D16M1I20M5I4M1I4M6I11M1D6M1D13M1D4M1D3M1D4M1I4M2I21M2D3M2I19M1D7M1D6M1I35M2I22M1D59M2I19M1D4M1I11M1D6M1D20M2D3M1D4M1I6M1D1M1D35M1D7M1I6M1I4M1I4M1D41M1D11M1I5M1I14M1D15M1D4M1D10M1I3M1D13M1D37M1D7M2I17M2D6M1D16M1I18M1D7M2I16M1D5M1I36M1I34M1D10M1D22M1D15M1D36M2I3M1D5M1D40M2I6M1D12M1I2M1I8M1D5M1I29M1I29M1I8M1D4M1I11M1D14M1D3M1D43M1I1M2I3M1D5M2D5M1D34M1I39M1I25M2D9M1I7M1I11M1D9M1I13M1I6M1D8M	*	0	0	AGAAGGAAAGATGATTCGACAGAAGGACTTAGGGACGGCGTGGGTGAGTTGGAATCTTAATGTTGCTGCTCGAAAGGAAAAATATTTTCAGCAAATGGACATGCGAGACACAATGACACGGACCCACTAACAAGATCTAGAAAGGATAACCTTTATGCTCTCAGAAAAATAGAGGACATGGAGTAGAGTGCGGGGAAATTTTTTTAGTGTGAAATGAGTAGGAGTTTGGGAAACAAAGACAACGAAGACGGAAGTCCGAGTATTTAGATGAGAGGAAATAAAGAGAAGTAAGGACATAGTTGGGTTGAACAATATTGTGCCGTTACAAGGAGAGATATAAGAGCCTAGCCGCATCTGACCTAGCTTTACTACAAAAAGAGTAGGAGTGATAATCCTACTACAGTTGTATTCAAAACAGTTTTAATATTTTAGAATTACGTGATTAATATTTTTTCAATATTAAATTTATTCTTCAATTTTTAAAGCCATAGATCGAAGTACCATTGTACCTTGTTGGTACACCAGGAACATTTTTATGTACAGTTTAACATTATGCAAATACATAATGCATTTAATATAGACGTGAATGTAGGCTCTCGGATGTAATACACCTGAAATTCAAAAAAAGAAATAGTAATTGTAAGAAAGTCAAAAAATGAGAGGACGAAACTTTTGGTGAACAAATTAATTATGTTGCACTGTATAAAAAAAACTTTTGGAAGAAAGGACTTTCATGCTGTTGTGGACGTAAAATGAAAAAAATTTGTTGCTTATAGGCAGTACGGTGATGCTATTGTCAGATAATATTTGTCATTTTTGTCAGAGAAAATTTTGTTGAAGAATATTTTGTCGTCAGACATTGACAACTCAAGTTTGCTTGGGAAAAAGTTTTAGAACATTTTGACTTTTCTGAATATTTTAAAAATAAAAGATGTACCAGGTGTAATTACCCCACAGGTTCTAAAGGGTATTGTACATATTAATATCCTTCCTGATCGCATCTAAAGAGAGAGAAAGACATGTCTGCGGAACTGTGGGGCAGATGTTTGAGTTTCAATAAGAAGGGACTGTGGGATTCGAGCCCACTAGGGTTCAAATCATAATGCGATTTATTTAGGATATCTGACGATAGCATTCAGTGAGAGGAGGAAGTTTCCGGCGACGATGAGTCTGAGTGTCTTACCCCCCCGGTGACTTTGAATTTTAAGATAATATGCCGCTCGTCTGCGTGAGGGTTGTTCATAGAACTAGAATATGCGTGGGTATAGTTCGAGGGATGAGGTATGTGATGTATAATATGCGCTTGCGTCTGTACTGTATTAAAACAACTACCGAAAGACAAGCCCGACACTGGGTGACGAGCAAAGAGAAAAAGGAGACTATATGAGCACGAGGGTCTTGCACGGGTGACCCTTTTCTGAACCTGCGGCCTGGATCACCTGGCAGTGGCTGGCCCTCCGAGGTGTACTATCGCCCCTCGGCGCCGTGAAGCTGCTCGCACCCCAGCGCGTCGTCCGCCTCGTTGGGCTCGCCAAGCCAATTCGTAAACTCACGAGAGCGGAGCTGGTGGGGAAGGATCTTCGTCTCACCACGATCGAGCTGCCCGCGTTAACTCCAGCCCTGTGCCCGCGCTTTTAACTTCGCTGCTGCTGACCAGTGTGCTGCGTGCTCCTTAACAGCATTAGAGCATTCAGAGTCAGGGGGATGCTCCATAAAAAAAAAGACGACGGCCTTCCCTAAACAGTGTACAACTATTTTTTACCAGATAAATTTTCGTGATGAAGGAATATGCATGGTATTCTGACGAGCGATAGTAATACGCAGGTCGCATGTACTAGCAGGACAAGTGAATAGGCTGCTGTGCTGTCCAAGCAGCTCACTCAGTCCCATATCGGCTAGTCAACCGGTGTATAATGTCGCTCAAAATTTCCATGTTGGCTGCCCCCAGGAACAATGGGGTTACACGTCACAAGGGTGGTAGCTCAGTTGCTCGAGAACATGTGCCGTGCACGATGCTGCAGTTTTAAATTGTTGTCAACATTCGCTTTTCTCCTACTTGGGGGCCAACAAATGGCAACGGGCGCCAGCGAACGCTCGTAGCTCTATTATGTACGCGGTGGAGGCGGAGCCTCGTGGACACTGTGGAGGTAGTCGTTCCATAGCCATAGGACCCCCCAAGCTAGCACTTGCACGGTGTCCTAGATTTATGTCATCGACAAGGTAATGGAGGTGCATATGCGTCGTGAATGGATAGTTGGATGCACACGCAACCAATGCTTTCAACAGTTGCTTCAAAACAAATGTTCGTTGTGGAGGCAGTCCAGCCTTCGGGACTACTCCTTCTACAAACGTATACAGGCGGCAATTAGTGTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![M::worker_pipeline::4302.783*13.85] mapped 38927 sequences
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	NM:i:327	ms:i:2798	AS:i:2798	nn:i:0	tp:A:P	cm:i:43s1:i:585	s2:i:88	de:f:0.1133	SA:Z:chr4A,158586004,-,16030M375D2368S,60,2220;	rl:i:0







```

**Comment by 909089617xx** [comment] 2019-03-11 07:54
Hi, Heng 
here is the picture,Does that make sense?
![image](https://user-images.githubusercontent.com/33317454/54107975-b00aa380-4415-11e9-8195-4482e885438e.png)

**Comment by wdecoster** [comment] 2019-03-11 07:56
@LipengKang did you align using `nohup`? It seems stderr and stdout got mixed in your file.

**Comment by LipengKang** [comment] 2019-03-11 08:01
@wdecoster
 yes. I used " nohup minimap2  -ax map-pb  ref.fa pacbio-reads.fq > aln.sam & " 
there are also some report lines  in head and tail of sam files. 
Thank you. I get it!

**Comment by lh3** [comment] 2019-03-11 11:47
Duplicate of #350.

Don't use nohup. You may also use option `-o` but that is discouraged.

**Closed by lh3** 2019-03-11 11:47 UTC
Labels: duplicate

**Comment by 909089617xx** [comment] 2019-03-11 11:55
Thank you very much, I get it!
