### ISSUE TITLE
nohup makes minimap2 throw its messages inside the alignemnt output file!

### ISSUE THREAD

**Issue by alphahmed** [lh3/minimap2#555] opened 2020-02-13 01:52 UTC
I tried to prefix my minimap2 with nohup, and end it with bg's '&' symbol, the output sam had the minimap2 progress messages thrown all over the place inside the sam file, instead of making a companion nohup.txt file.

**Comment by lh3** [comment] 2020-02-13 02:59
Duplicate of #350 and #359. In brief, use "-o" or avoid nohup.

**Closed** 2020-02-13 03:00 UTC
Labels: duplicate, question

**Comment by alphahmed** [comment] 2020-02-13 04:32
Thanks!

**Comment by moriarais** [comment] 2024-12-09 09:01
It is better to add a comment to avoid using `nohup ` in the read.me file. Thanks
