### ISSUE TITLE
Fails to compile on ppc64el POWER 9

### ISSUE THREAD

**Issue by shawnl** [lh3/minimap2#395] opened 2019-05-09 01:07 UTC
```
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  main.c -o main.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  kthread.c -o kthread.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  kalloc.c -o kalloc.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  misc.c -o misc.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  bseq.c -o bseq.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  sketch.c -o sketch.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  sdust.c -o sdust.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  options.c -o options.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  index.c -o index.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  chain.c -o chain.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  align.c -o align.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  hit.c -o hit.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  map.c -o map.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  format.c -o format.o
format.c: In function 'mm_write_sam3':
format.c:391:36: warning: variable 'this_rev' set but not used [-Wunused-but-set-variable]
  391 |  int this_rid = -1, this_pos = -1, this_rev = 0;
      |                                    ^~~~~~~~
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  pe.c -o pe.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  esterr.c -o esterr.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  splitidx.c -o splitidx.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -DHAVE_KALLOC  ksw2_ll_sse.c -o ksw2_ll_sse.o
cc: error: unrecognized command line option '-msse2'
make: *** [Makefile:51: ksw2_ll_sse.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by lh3** [comment] 2019-05-09 01:26
Duplicate of #393. Minimap2 doesn't support POWER.

**Closed by lh3** 2019-05-09 01:26 UTC
Labels: duplicate, question

**Comment by junaruga** [comment] 2019-05-09 22:38
I sent pull-request to propose the ppc64el on this repository.
